### ISSUE TITLE
Pitch value in Crazyflie::sendSetpoint method

### ISSUE THREAD

**Issue by AliGriv** [whoenig/crazyflie_cpp#16]
Hello,

I had been looking into your library and comparing it with the python implementation in [Cflib Repository](https://github.com/bitcraze/crazyflie-lib-python), a nuance difference caught my eye. There is a negative sign behind pitch value [here](https://github.com/bitcraze/crazyflie-lib-python/blob/4b3ff21219aaebe540899c8904d7827cd132d1af/cflib/crazyflie/commander.py#L80) which is not the same as the [cpp implementation](https://github.com/whoenig/crazyflie_cpp/blob/aedb2827f8b574a9cbd75fad4d0da8a1530ec1c3/src/Crazyflie.cpp#L175). I was wondering what is the source of this difference? In my own application, it seemed that I should go with the negative sign (although I haven't been completely successful using crazyflie_cpp for my project). 
Previously, I was able to successfully use [Cflib Repository](https://github.com/bitcraze/crazyflie-lib-python) to fly my drones using external motion capture system, however, I need to switch to C++ for my main project and I'm still struggling with it. I would be grateful if you can provide me some information about [this function](https://github.com/whoenig/crazyflie_cpp/blob/aedb2827f8b574a9cbd75fad4d0da8a1530ec1c3/src/Crazyflie.cpp#L169) and its differences with its [python counterpart](https://github.com/bitcraze/crazyflie-lib-python/blob/4b3ff21219aaebe540899c8904d7827cd132d1af/cflib/crazyflie/commander.py#L65).

Thank you.

**Comment by whoenig** [comment]
This might be just for historical reasons. It is certainly wrong in the firmware (w.r.t. to a right-handed coordinate system) and different libraries try to "fix" it at different levels. CRTP is the lowest level, so when you write your code in C++ you might just need to call the sendSetpoint() function with a negative sign on your side.

If you are interested into using a mocap, please also check out the https://crazyswarm.readthedocs.io/, which supports various mocaps and could be seen as a "reference implementation" on how to use crazyflie_cpp. While the Crazyswarm relies on ROS (and is therefore bound to Ubuntu), it is entirely possible to remove the ROS dependency.
