### ISSUE TITLE
takeoff() and land() functions don't seem to do anything

### ISSUE THREAD

**Issue by benkuper** [whoenig/crazyflie_cpp#9]
Hey wolfgang,
I'm back in developping LaMoucheFolle and switching over to fully use your lib. Almost everything is implemented, and I modified the lib to work on windows (VS2019) as well (I'll post a PR when i see it working).

I'm testing without any calibration so the drone's detected position is getting crazy.
The sendPositionSetpoint function seems to work as the propellers start spinning when I send the commands, and the stop() function as well.
However, the sendSetPoint (ypr thrust command) is not doing anything, and the takeoff and land() functions as well.
Is there a specific configuration that needs to be met for those commands to work ? Have this groupmask set up, or using the mellinger controller ?

Thanks !

**Comment by whoenig** [comment]
Hi Ben,
Great! Once you get it working, I am happy to look at the PR and also add continuous integration for Windows to not break the build in the future.

Without external system, you will at least need the flow deck for successful flights.

There can be two reasons why sendSetpoint is not working:
a) sensors not (yet) calibrated (you can check by looking at the console output or LED blinking frequency).
b) You didn't send an unlock command (sendSetpoint(0,0,0,0)) prior to your actual command.

For takeoff() and land() you need to enable the high-level mode first by setting the parameter "commander.enHighLevel" to 1. No need to deal with the groupmask (use 0) or changing the controller (works with both controllers).

**Comment by benkuper** [comment]
All the answers I needed !
Thanks, I'll try to wrap that up tomorrow
